Suggest early involvement
git/git.github.io pull request #503
Opened 2021-05-17 09:12 UTC by chriscool

2021-05-19 09:44 UTC, gitster requested changes

2021-05-19 09:44 UTC, gitster commented on General-Application-Information.md
> +yet being pursued by a serious applicant who started getting involved
doubt you need to say :serious" here.

2021-05-19 15:14 UTC, chriscool commented on General-Application-Information.md
> +yet being pursued by a serious applicant who started getting involved
Ok, I removed it. Thanks for taking a look!

2021-05-20 07:26 UTC, chriscool commented
Actually I messed up and commits in this PR have been merged in #502 so I had to apply Junio's suggestion later in 6f25818c226b4dc02a0d9106603ee05a23a10025. Closing this now.

2021-05-20 07:26 UTC, closed without merging